# Generated by Django 2.2 on 2020-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_records_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='picture',
            field=models.ImageField(null=True, upload_to='athlete/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='picture',
            field=models.ImageField(null=True, upload_to='coach/'),
        ),
    ]
